//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta_Usuario
    {
        public int idCuenta_Usuario { get; set; }
        public string usuario { get; set; }
        public string correo { get; set; }
        public string contraseña { get; set; }
        public Nullable<int> Usuario_idUsuario { get; set; }
    
        public virtual Usuario Usuario1 { get; set; }
    }
}
