//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relaciones_Amistad
    {
        public int idAmigo { get; set; }
        public Nullable<int> Usuario_idUsuario { get; set; }
        public Nullable<int> Estado_SolicitudAmistad_idEstado_SolicitudAmistad { get; set; }
    
        public virtual Estado_SolicitudAmistad Estado_SolicitudAmistad { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
